### PR TITLE
Fix Emacs 25 compatibility

### LINKED ISSUE #47: Emacs 25 compatibility
It seems that stan-mode does not work with Emacs 25.

It fails to load:

```
Eval error in the ‘c-lang-defconst’ for ‘c-:$-multichar-token-regexp’ in stan-mode:
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setver’ for ‘c-:$-multichar-token-regexp’ (source eval): (wrong-type-argument stringp (\, "%"))
```

And fails to indent:

```
c-looking-at-decl-block: Wrong type argument: stringp, nil
```

Tested with RC1.

### PR DESCRIPTION
**Pull request by lionel-**
Closes #47

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Looks like we haven't got the copyright release in the stan-mode
directory.  

Lionel --- is this code copyright by you or does someone else own
it (like a company or university), and if so are they OK with
you releasing it open-source?  I don't know what the license is
on stan-mode, but it should be made explicit and contributors should
acknowledge they're OK with the license.

Sorry for the CYA legal crap (pun intended).

- Bob

**Comment by lionel-** [comment]
Hmm does this even qualify for copyrighted content? ;)

In any case sure, this is meant to be included with the same licence as stan-mode.

**Comment by bob-carpenter** [comment]
In the U.S., copyright is automatically assigned to the
author of any text or computer code. 

For others to be able to legally use text or code, the
copyrighted material must be explicitly licensed for such
use by the copyright holder.  Just saying "common domain"
or "this is trivial" isn't enough.

Also, are you the copyright holder?  Often people's employment
contracts require authors to assign copyright to their employer.
Mmost universities require this, even if most university employees
don't realize it.  It's why my copyright notice says
"Columbia University", not "Bob Carpenter".  Columbia's given
us a signed waiver allowing us to release current and future work
on Stan under the BSD or other open-source licenses in perpetuity,
which is all we need.

Again, sorry to be such a pain on this, but now that the project's
so big, we want to cover the project's ass.

Having just written all this, I'm going to post about it on
Andrew's blog.

**Comment by lionel-** [comment]
You're right, looks like my university owns any software I write for my research. WTF!?!

It's a bit fuzzy what is meant by "for my research" though. And I'm pretty sure that the three lines of code I wrote in this PR do not qualify as original work and so cannot be covered by copyright.

Anyway, it appears those fixes are not sufficient. Indentation after curly blocks throws an error. I traced it back to this defconst:

```lisp
(c-lang-defconst c-nonsymbol-token-regexp stan nil)
```

This is used in a regexp lookup which expects a string and so this cannot be nil. A quick workaround is to set it to `"."`. Doesn't seem to break anything. Though given the name of this variable it probably makes more sense to set it to `"\\s."`, which is the Emacs character class for punctuation symbols.

Also I guess the other defconsts of regexps to nil may be liable to create this sort of bug in the future, not sure what's the right thing to do here.

**Comment by lionel-** [comment]
Ok, I found the root of all issues. A sneaky code typo :)

Now stan-mode can be derived from one of the canonical cc-mode as is intended by the maintainer:

> The canonical way to create a mode derived from CC Mode is to derive from, say, c-mode, call c-add-language, then specify the values of the language variables which differ from those of c-mode.

I've opted for `c-mode` rather than `c++-mode` because my guess is that the latter implements a lot of logic that is not needed for the Stan language (but that's only a guess).

**Comment by jrnold** [comment]
Thanks, @lionel- !  Sorry about the delay, I've had too much academic work to get to this - and I've been spending more time using atom than emacs lately. You're right this is the better way to do it. I had started with writing it by inheriting from `c++-mode`. But because that sets so many different settings (and the number of settings are enormous), I did the wrong thing and set everything manually so I at least understood what was happening. It turns out that was the wrong choice, and I hadn't anticipated it breaking so much.

**Comment by lionel-** [comment]
There are other cc-modes out there that do not call `c-add-language`, so that was not necessarily a bad decision. The root of all the breaking was this:

```lisp
(c-lang-defconst c-operators
   stan '((postfix "[" "]" "(" ")")
 	  (postfix-if-paren "<" ">")
 	  (postfix "'")
 	  (left-assoc "^")
  	  (prefix "!" "-" "+")
  	  (left-assoc "./" ".*")
  	  (left-assoc "\\")
  	  (left-assoc "/" "*", "%")   ;; <--- Notice the comma
  	  (left-assoc "+" "-")
  	  (left-assoc "<" "<=" ">" ">=")
  	  (left-assoc "!=" "==")
```

This created a list containing a comma symbol whereas cc-mode expected a list containing only strings, hence the issues with all kind of functions.

**Comment by jrnold** [comment]
Well, now I feel really stupid.

**Comment by lionel-** [comment]
No worries, the exact same thing happened to me yesterday!

https://github.com/lionel-/fontquiver/commit/9c9102d77e153db39d961a3d3c7fd9bf98db35d8

**Comment by bob-carpenter** [comment]
> On Aug 26, 2016, at 5:38 PM, Lionel Henry <notifications@github.com> wrote:
> 
> You're right, looks like my university owns any software I write for my research. WTF!?!
> 
> It's a bit fuzzy what is meant by "for my research" though.

The law in general and contracts in particular are even less
well-defined than the C++ spec (C++l leaves a lot of behavior
up to the compiler).  

> And I'm pretty sure that the three lines of code I wrote in this PR do not qualify as original work and so cannot be covered by copyright.

Size doesn't matter, nor does the fact that it's work added
to or written on top of other work.

Thanks for helping out.

- Bob

**Comment by lionel-** [comment]
> Size doesn't matter

This is true, but whether the code or the changes in question constitute an original piece of work does matter. This is clearly not the case here. I've removed a bunch of loc, removed one character that was causing bugs, then uncommented a line and removed two characters from it. So technically I did not even write anything, I unwrote ;)

You can close this PR and commit the fix yourself if you prefer.

Your rules are even more stringent than Richard Stallman's by the way. He accepts patches of less than 15 lines without copyright assignment in his projects, and he's advised by copyright professionals on legal matters like this.

**Comment by bob-carpenter** [comment]
We can't afford IP lawyers.  So we may be harder in
requiring a statement of ownership for small changes,
we don't require anything in writing like this:  

https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html

Much of this is in the grey area of wait-and-see-what-the-courts-do.
We just figured asking everyone to state that they own the copyright
and have the right to distribute it is easiest.

But who knows?  It's the wild west out there, with a landscape
full of do-gooders, trolls, and corporate intrigue.

**Comment by rcorty** [comment]
Maybe this PR needs to be merged and sent to MELPA? (I don't know how MELPA works)

**Pull request merged**
