### PR TITLE
Version 10.0.0: company, eldoc, and flycheck integration

### PR DESCRIPTION
**Pull request by kaz-yos**
Here is a screencast.
example

This major update adds several new packages:
- [company-stan](https://github.com/stan-dev/stan-mode/commit/1b1a537936422adb50a2b7677203ed8c37168875) for auto-completion
- [eldoc-stan](https://github.com/stan-dev/stan-mode/commit/d3c045c74cce32121e0e9c13a7222c537a14bbf7) live help for function arguments
- [flycheck-stan](https://github.com/stan-dev/stan-mode/commit/0d875ad012d85c898fe6682b62df6182295b6871) on-the-fly syntax checking with stanc

Two existing packages have been updated:
- [stan-mode](https://github.com/stan-dev/stan-mode/commit/a6104ecf33e134192a42a62c0912e72c5bc64019) for indentation and syntax highlighting
   - Deprecate # comments while handling #include differently
- [stan-snippets](https://github.com/stan-dev/stan-mode/commit/f7ccceb91039dfcff45934326d0050f7e4d1713b) for function argument completion
  - Support | as an argument separator where appropriate

All packages include automated testing (`test-*.el` files) to ensure their behaviors. See [here](https://travis-ci.org/stan-dev/stan-mode/jobs/587276519#L1509).

The minimum requirement for the Emacs version is 25.1.

The human-based testing procedures for the PR are as follows:
- Clone the development branch somewhere and install packages as described [here](https://github.com/stan-dev/stan-mode/tree/develop#via-github)
- Configure these packages in your `.emacs.d/init.el` as described [here](https://github.com/stan-dev/stan-mode/tree/develop#configuration)
- Open the `example_schools_mod_ncp.stan` example file to examine if the behaviors in the screencast reproduces:
  1. Delete the line `mu ~ normal(0,10);` in the `model` block.
  2. Type `muu ~ nor` and wait to see if `company` brings up completion candidates. Choose `normal`
  3. Hit TAB to see if `yasnippet` insert an argument template `(mu, sigma)`. The cursor should be at `mu` and allows you to enter 0. Hit TAB to move to `sigma` and enter 10. Hit TAB again to come out and enter ;.
  4. During the operations within the function arguments, the mini-buffer at the bottom should be showing argument help `(reals mu, reals sigma)` with the current argument highlighted by `eldoc`.
  5. The misspelled `muu` should be underlined by `flycheck`.
  6. Once you move the cursor to `muu`, `flycheck` should bring up "no such variable" error information.
  7. Fixing `muu` to `mu` should eliminate the underline and message.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
I don't know enough about stan-mode to review this, but I'd be happy to just approve these PRs when they're ready.  Thanks for working on it.

**Comment by kaz-yos** [comment]
Hi @bob-carpenter, thanks for checking on this! I'll fix the issue with Travis-CI and finalize the pull request.

**Comment by kaz-yos** [comment]
The PR-only failure is likely related to this Melos issue: https://github.com/melpa/melpa/issues/300

**Comment by kaz-yos** [comment]
Technically, I can just merge this myself or even just push without a PR, but it's probably a good idea to document a major update. I wonder if @jrnold and/or @syclik could try this out as outlined in the first post.

**Comment by seantalts** [comment]
Whoa, the screencast on this looks awesome! We should definitely put a link to that on the blog or something. 

Does flycheck just work with any arbitrary compiler output?

**Comment by kaz-yos** [comment]
`flycheck-stan` picks up all "Info:..." pattern and error patterns listed [here](https://github.com/stan-dev/stan-mode/blob/develop/flycheck-stan/error_msgs.txt).


These were extracted from [this file](https://github.com/kaz-yos/stan/blob/b3add46b4451fdca87f281c2f9d00e06532f1f96/src/stan/lang/grammars/semantic_actions_def.cpp) by some [basic pattern matching](https://github.com/stan-dev/stan-mode/blob/develop/flycheck-stan/flycheck-stan-error-msgs.el#L56-L64).


As stated [here](https://discourse.mc-stan.org/t/structured-error-output-format-for-stanc/10342/3), things will be much easier if all error messages are prefixed with "Error: " or some easy pattern.

**Comment by bob-carpenter** [comment]
+1 to that.  In particular, we shouldn't have individual exceptions saying "error", but the top level thing that prints to users should say that it's an error or warning or whatever.

**Comment by kaz-yos** [comment]
Please keep this unmerge for now. I realized the packages have to go through the review by the maintainers of the MELPA emacs package repository. Users will experience breakage if we merge before MELPA accepts the package definition updates (https://github.com/melpa/melpa/pull/6444).

**Comment by kaz-yos** [comment]
The new packages are still queued for MELPA review https://github.com/melpa/melpa/pulls

**Comment by kaz-yos** [comment]
@seantalts, is this the file I can find the stanc3 error messages?
https://github.com/stan-dev/stanc3/blob/master/src/frontend/Semantic_error.ml

**Pull request merged**
