### PR TITLE
Update stan-mode for stan 2.19.0

### PR DESCRIPTION
**Pull request by kaz-yos**
This pull request updates the stan-mode for the latest stan (version 2.19.0).

For a historical record, the first commit updates the keywords-list to 2.17.0, which was the version in the language definition submodule repo *prior to* my 2.19.0 update (https://github.com/jrnold/stan-language-definitions/commit/8fe215882ef7cd60b5f6be35d67e8909a59bc00e).

The second commit updates the language definition submodule and all relevant files to 2.19.0 via `make all`.

There are no new features being added by this pull request.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
@jrnold or @syclik :  any chance one of you could review this?

If not, I can try to install it and then I can approve if it works.

**Comment by bob-carpenter** [comment]
@kaz-yos --- please remind me in a few days to review this if we haven't heard from the others and I'll try to install and approve.

**Comment by kaz-yos** [comment]
I'll remind in a couple of days. I'm currently working on feature enhancements: `company-stan` and `eldoc-stan`, which I will submit after this PR is merged.

**Comment by kaz-yos** [comment]
@bob-carpenter, I just realized the second commit introduces typos (`binomia_*`) that are in the upstream data file (https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/tools/stan-functions.txt#L60-L62). I'll take this PR down and come back with a cleaner one.

**Comment by jrnold** [comment]
Sorry for not replying earlier. I can approve it when it comes in, but I would like to relinquish maintaining emacs-mode. It's been a while since I've used emacs, so I'm not in place to catch errors or fresh enough in emacs-lisp to fix them.

**Comment by bob-carpenter** [comment]
Thanks.  We can get someone else to review this one.

May I ask what you're using instead of emacs these days and if there's a Stan mode for that?

**Comment by jrnold** [comment]
Moved to Atom, but now mostly use VS Code. I wrote a stan-mode for Atom. None for VS Code. Since moving to a new job, I've been using Bayesian stats and Stan less 😢 , though trying to get more Bayesian stats here.

**Comment by kaz-yos** [comment]
I have opened another pull request fixing the issues stated above.
https://github.com/stan-dev/stan-mode/pull/57

**Pull request closed without merging**
