### PR TITLE
v9.3.0 to support Stan 2.19.0

### PR DESCRIPTION
**Pull request by kaz-yos**
This is a minimalistic update to support Stan version 2.19.0 based on the 2.19.0 language definitions file in the stan-language-definitions repo (https://github.com/jrnold/stan-language-definitions), which I currently co-maintain with @jrnold.

CHANGES:
- Update `stan-mode/stan-keywords-lists.el` to support syntax highlighting based for Stan 2.19.0
  - Drop obsolete function names such as `binomial_cdf_log`
  - Add new function names such as `beta_proportion_rng`
- Update, add, or drop snippets following the above changes

For a historical record, the first commit updates the keywords-list to 2.17.0, which was the version in the language definition submodule repo *prior to* my 2.19.0 update (https://github.com/jrnold/stan-language-definitions/commit/8fe215882ef7cd60b5f6be35d67e8909a59bc00e).

Once this is merged. I'll work on the pull request for v10.0.0.

PLANED CHANGES for v10.0.0:
- `company-stan` for `company-mode`-based completion
- `eldoc-stan` for `eldoc`-based live help on function arguments
- Automated testing with `buttercup`

### CODE REVIEW

**Comment by syclik** [comment]
Awesome! I just saw the old PR. Could you let me know how I should test this? (What should I look for when I test it?)

**Comment by kaz-yos** [comment]
That's a good question! I didn't think about that deeply enough as it "kind of worked" for me. This current PR is supposed to update the language definitions only, so it should do the following as stated in [README.md](https://github.com/stan-dev/stan-mode/blob/master/README.md).

- `stan-mode` is a major mode for editing Stan files. Its current features include:
  - syntax highlighting
  - indentation
  - [imenu](http://www.emacswiki.org/emacs/ImenuMode) support for blocks, variables, and user-defined functions.

So the corresponding "interactive tests" would be:

- syntax highlighting
  - The [`demo.stan`](https://github.com/jrnold/stan-language-definitions/blob/master/examples/demo.stan) file should look decent with block names, type names, function names, comments, and strings having different faces (colors depend on your color theme).
  - I'm not quite advanced enough as a Stan user to tell if the [`demo.stan`](https://github.com/jrnold/stan-language-definitions/blob/master/examples/demo.stan) itself is up-to-date as an example. Please let me know if you find this insufficient.
  - Selecting a region and `M-x comment-dwim` (`M-;`) should comment or uncomment the region depending on the current comment status.
- indentation
  - It defaults to two-space indentation.
  - If you intentionally break indentation, select that region, and do `M-x indent-region`, it should recover the indentation.
- `imenu` support for the current buffer ( I have to admit I didn't know `imenu` before).
  - `M-x imenu` should let you choose among Bock, Function, and Variable.
  - Choosing one should then allow you to give the options that exist in the current buffer.
  - Making a choice should take you to the location in the buffer.

**Comment by jrnold** [comment]
I never got around to figuring out how to do unit tests in Emacs, so I only tested it manually by using the mode with files like @kaz-yos described and also using `make compile` to pick up some errors.

This is awesome work 👍  If it's okay with @syclik, I would suggest that you take over maintenance of this.

**Comment by kaz-yos** [comment]
FYI, I figured out how to test indentation and syntax highlighting so these are coming to the next major update (working version https://github.com/kaz-yos/stan-mode/blob/new-features/stan-mode/test-stan-mode.el). I found this very helpful: https://emacs.stackexchange.com/questions/45775/how-can-i-unit-test-my-font-face-rules

The comment style has been simplified in Stan, so I’m considering if this part can be simplified in ‘stan-mode’.

**Comment by bob-carpenter** [comment]
Thanks. I'll just go ahead and merge as I don't think we have anyone to review this.

**Comment by syclik** [comment]
Absolutely! Please take over!

**Comment by kaz-yos** [comment]
@bob-carpenter, could you tag the latest commit as `v9.3.0` so that MELPA Stable can take it up.

@jrnold and @syclik, I'm happy to take over the maintainer role. `v10.0.0` with `company-stan` for autocompletion, `eldoc-stan` for live argument help, and `flycheck-stan` for on-the-fly `stanc` is on the horizon. Do I get push access to the `stan-dev/stan-mode`? What's the workflow? Is it still PR-based regardless of push access?

**Comment by kaz-yos** [comment]
@bob-carpenter, I believe you only need to create a release on the Github.
1. Visit https://github.com/stan-dev/stan-mode/releases
2. Draft and create a release with the message outlined below with the version `v9.3.0`.

CHANGES:
- Update `stan-mode/stan-keywords-lists.el` to support syntax highlighting based for Stan 2.19.0
  - Drop obsolete function names such as `binomial_cdf_log`
  - Add new function names such as `beta_proportion_rng`
- Update, add, or drop snippets following the above changes

Then the MELPA-Stable (https://stable.melpa.org/#/) system should pick up the latest release.

**Comment by bob-carpenter** [comment]
OK.  I think that worked.  

Can I somehow give you permission to do this going forward?

- Bob

**Comment by kaz-yos** [comment]
I confirmed a new release `v9.3.0`. This should trigger the MELPA-Stable system to take up the latest.

Regarding permissions, I would appreciate if you could promote me to the same permission level as @jrnold for the `stan-mode` repo.

**Comment by bob-carpenter** [comment]
OK.  I invited you to be a maintainer.

> Regarding permissions, I would appreciate if you could promote me to the same permission level as @jrnold for the stan-mode repo.

**Pull request merged**
